### ISSUE TITLE
invalide date

### ISSUE THREAD

**Issue by mikolg** [sahsanu/lectl#1]
When I call it fails with next errors:

**./lectl connectivegames.com**
lectl 0.6 (2016-April-04)
2016/**Июнь**/04 09:26:58 - Checking certs for connectivegames.com
date: invalid date '\321\201\320\265\320\275 01 17:34 KRAT 2016'
date: invalid date '\321\201\320\265\320\275 01 17:34 KRAT 2016'
...

I've replaced "LANG=C;" with "LANG=en_US;" and it works for me. Output is below.
Please check if it's possible to apply this fix.

**./lectl_en_US connectivegames.com**
lectl 0.6 (2016-April-04)
2016/June/04 09:41:03 - Checking certs for connectivegames.com

I have found 45 non expired certificates for domain connectivegames.com and its subdomains *.connectivegames.com

**Comment by sahsanu** [comment]
Hello @mikolg,

Could you please tell me what is your operating system and version and show me the output of command **`locale`** and the command **`locale -a`** ?.

Thank you.
sahsanu

**Comment by mikolg** [comment]
Hi,

Here is output

**lsb_release -a**
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:    16.04
Codename:   xenial

**uname -a**
Linux mikolg 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**locale**
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=

**locale -a**
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
ru_RU.utf8

**Comment by sahsanu** [comment]
@mikolg,

I've updated lectl to version 0.7: https://raw.githubusercontent.com/sahsanu/lectl/master/lectl 

Could you please check this last version and tell me whether is it working fine in your computer?.

Thank you.
sahsanu

**Comment by mikolg** [comment]
Yes. it works. thanks.

**Comment by mikolg** [comment]
I've got new version and issue is returned.

./lectl connectivegames.com
lectl 0.7 (2016-June-04)

2016/August/23 18:33:21 - Checking certs for connectivegames.com

date: **invalid date** 'Jul 24 02:10:00 2016 GMT'
I have found 83 non expired certificates for domain connectivegames.com and its subdomains *.connectivegames.com

**Comment by sahsanu** [comment]
Hello @mikolg,

I didn't change anything since the version you tested and worked fine on your server, is the same machine?, please send me the output of **`locale`** and **`locale -a`**

**Comment by mikolg** [comment]
Yes. You are right. Everything fine on previous host and error on new one.

**lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial

**uname -a**
Linux mikolg-tosh 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**locale**
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

**locale -a**
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
ru_RU.utf8

**Comment by sahsanu** [comment]
Hello @mikolg,

I've installed the same Ubuntu version in a Virtual Machine, even installed locale ru_RU.UTF-8 but I'm not able to reproduce your issue.

Inside the script, the line **export LC_ALL=C** should cover the locale problem and the date command should work as expected, indeed, the error that is shown:

`date: invalid date 'Jul 24 02:10:00 2016 GMT'`

is really weird because the date format is correct, could you please show me the results of these commands?:

```
date -d "Jul 24 02:10:00 2016 GMT" +'%Y-%b-%d %H:%M %Z'
date -u -d "Jul 24 02:10:00 2016 GMT" +'%Y-%b-%d %H:%M %Z'
```

and

```
export LC_ALL=C
date -d "Jul 24 02:10:00 2016 GMT" +'%Y-%b-%d %H:%M %Z'
date -u -d "Jul 24 02:10:00 2016 GMT" +'%Y-%b-%d %H:%M %Z'
```

Also, send me the output of:

`bash -x ./lectl connectivegames.com`

The output should be large so upload it to https://gist.github.com/ or http://pastebin.com/ or the site that you prefer ;).

Thank you.

**Comment by mikolg** [comment]
lectl log is here https://dl.dropboxusercontent.com/u/63349586/lectl.log.gz

Date output:

```
+ date -d 'Jul 24 02:10:00 2016 GMT' '+%Y-%b-%d %H:%M %Z'
date: invalid date ‘Jul 24 02:10:00 2016 GMT’
+ date -u -d 'Jul 24 02:10:00 2016 GMT' '+%Y-%b-%d %H:%M %Z'
2016-Jul-24 02:10 UTC
+ export LC_ALL=C
+ LC_ALL=C
+ date -d 'Jul 24 02:10:00 2016 GMT' '+%Y-%b-%d %H:%M %Z'
date: invalid date 'Jul 24 02:10:00 2016 GMT'
+ date -u -d 'Jul 24 02:10:00 2016 GMT' '+%Y-%b-%d %H:%M %Z'
2016-Jul-24 02:10 UTC

```

**Comment by mikolg** [comment]
More strange logs:

```
+ date -d 'Jul 24 01:10:00 2016 GMT' '+%Y-%b-%d %H:%M %Z'
2016-Jul-24 08:10 +07
+ date -d 'Jul 24 02:10:00 2016 GMT' '+%Y-%b-%d %H:%M %Z'
date: invalid date ‘Jul 24 02:10:00 2016 GMT’
+ date -d 'Jul 24 03:10:00 2016 GMT' '+%Y-%b-%d %H:%M %Z'
2016-Jul-24 10:10 +07

```

**Comment by sahsanu** [comment]
Wow, yes, that is really weird, maybe something related to your timezone config, Check the timezone you are using:

`cat /etc/timezone`

and try to reconfigure it selecting the right time zone for your server (even whether it is the correct one, reconfig it):

`sudo dpkg-reconfigure tzdata`

**Comment by mikolg** [comment]
> dpkg-reconfigure tzdata

It's helped. Thanks,
