### ISSUE TITLE
Let's Encrypt certificate rate limit increased to 50

### ISSUE THREAD

**Issue by rihadik** [sahsanu/lectl#11]
Likely since August 1.

> The main limit is Certificates per Registered Domain, (50 per week). 

https://letsencrypt.org/docs/rate-limits/

So this should probably be increased.

`ratelimit='20'
`

**Comment by sahsanu** [comment]
Hi @rihadik,

I modified this limit in lectl version 0.16 (August 5th) so seems you are using an outdated version and you should update it.

Cheers,
sahsanu

**Comment by rihadik** [comment]
Oops, sorry and thanks! Closing this one.
