### ISSUE TITLE
Change error message?

### ISSUE THREAD

**Issue by jaykaypea** [sahsanu/lectl#17]
Hi @sahsanu! Thank you so much for this tool, it has been a huge help!

We just had someone who requested a rate limit adjustment put their domain in and it said they still had a 50 certs/registered domain/week rate limit (which is typically correct except for those who have a rate limit adjustment - which I know we don't have a publicly accessible API to see the changes for and there's no way you could get these changes).

Is there a way we could change the error message from this:

> Sorry, you can't issue any certificate, you already issued 50 certificates on last 7 days
> You could issue next certificate on DATE TIME UTC
> 
> Note 1: Keep in mind that if <<DOMAIN>> is included in PSL (Public Suffix List) the rate limit could only be applied to your subdomain instead of your domain.
> Note 2: Right now Let's Encrypt is implementing a new feature so if you renew the exact cert (with the same FQDNs) the rate limit could not apply to your domain if you try to renew it.
> 

To (something like) this:

> Sorry, you can't issue any certificate, you already issued 50 certificates on last 7 days
> You could issue next certificate on DATE TIME UTC
> 
> Note 1: Keep in mind that if <<DOMAIN>> is included in PSL (Public Suffix List) the rate limit could only be applied to your subdomain instead of your domain.
> Note 2: If you requested a rate limit adjustment for your domain or ACME account ID via https://letsencrypt.org/docs/rate-limits/ that change is not reflected here.
> Note 2: Let's Encrypt has a renewal exemption for the certificates/registered domain/week rate limit. More information can be found at: https://letsencrypt.org/docs/rate-limits/

Let me know if that works at all or if I can be of any further help! And thanks for doing this!

-Jenessa at Let's Encrypt

**Comment by sahsanu** [comment]
Hello @jaykaypea ,

Of course, I'll implement the suggested changes in the next version (in one or two weeks).

Thank YOU.
