### ISSUE TITLE
Use Tagged Releases

### ISSUE THREAD

**Issue by osterman** [sahsanu/lectl#8]
## what
* Add tagged releases

## why
* We would like to distribute `lectl` as part of our [`cloudposse/packages`](https://github.com/cloudposse/packages) distribution and would like to pin to a release
* The current releases page is empty

![image](https://user-images.githubusercontent.com/52489/42711515-056eb23a-869d-11e8-97e4-2b977fd63fdf.png)

**Comment by sahsanu** [comment]
Hi @osterman ,

I've created a release with current version v0.15.

Cheers,
sahsanu

**Comment by osterman** [comment]
Thanks!
